name: Go

on:
  push:
    branches: [ feature, master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v3
    
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-db: grpcgateway 
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build  # Add this to ensure docker waits for the build job
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/grpcgateway:latest

